const Types = {
  LOG_OUT: "LOG_OUT",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  LOG_IN: "LOG_IN",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_REQUEST_FINISHED: "FETCH_REQUEST_FINISHED",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
};

export default Types;
